'use strict';
import countTimer from './modules/countTimer';
import toglMenu from './modules/toglMenu';
import togglePopup from './modules/togglePopup';
import scroll from './modules/scroll';
import tabS from './modules/tabS';
import dataImage from './modules/dataImage';
import calck from './modules/calck';
import slayder from './modules/slayder';
import sendForm from './modules/sendForm';
countTimer('14 may 2020');
toglMenu();
togglePopup();
scroll();
tabS();
dataImage();
calck(100);
slayder();
sendForm();