'use strict';

import '@babel/polyfill';
import elementClosest from 'element-closest';
elementClosest(window);
import 'nodelist-foreach-polyfill';
import 'formdata-polyfill';
import 'es6-promise';
import 'fetch-polyfill';
import countTimer from './modules/countTimer';
import toglMenu from './modules/toglMenu';
import togglePopup from './modules/togglePopup';
import scroll from './modules/scroll';
import tabS from './modules/tabS';
import dataImage from './modules/dataImage';
import calck from './modules/calck';
import slayder from './modules/slayder';
import sendForm from './modules/sendForm';
countTimer('14 may 2020');
toglMenu();
togglePopup();
scroll();
tabS();
dataImage();
calck(100);
slayder();
sendForm();